#WAP TO SHOW DEMO OF LIST IN PYTHON
# HOW TO DE|FINE LIST
a = ["AMROLI","SUTEX","BCA","BBA","BCOM","BSC DSA","BSC IT","MSC IT"]
print(a)
"""
sdata =["DEVESHKUMAR KAILASHBHAI KALAL","HITEN SURESHBHAI KANANI","KUMARI NIKKI SHRI SOMNATH PANDEY","PATEL TRUSH PINKALBHAI","VARIYA DHARMIK JITENDRABHAI","ADITYA ARVINDBHAI DHAMELIYA","DARSHIT GIRDHARBHAI RADADIYA","HARSHIL NITESHBHAI BHINGARADIYA","KRISH BHAVESHBHAI PADARIYA","BHUMI NILESHBHAI CHAUHAN","HARSH JIGNESHBHAI JALODARA","FERAL SURESHBHAI KHUNT","KEYUR SANJAYBHAI NAROLA","PARTH SAVJIBHAI SARASIYA","RAHUL KAUSHIKBHAI SONPAL","PRINCE DINESHBHAI RAMANI","PARTH NILESHBHAI KAKLOTAR","YOGINKUMAR VIJAYBHAI SUTARIYA","TIRTHKUMAR PRAVIN VAGADIYA","DEVBHAI ROHITBHAI GOTI","HERI ATULBHAI MANDADIYA","SONANI SUJAL PRAKASHBHAI","HARSHIL DILIPBHAI MAKVANA","MANAN KISHORBHAI GOYANI","YAGNIK KISHORBHAI BOGHARA","RAHUL LAKHAMANBHAI SINDHAV","JEEL NITESHBHAI GOPANI","SRUSHTI JAGDISHBHAI GHASKATA","KISHAN SWAMINATH YADAV","MARVINKUMAR GHANSHYAMBHAI CHOVATIA","PRINSI MADHUBHAI BABARIYA","KARAN DIPAKBHAI GOHEL","KRISHA ASHVINBHAI PARMAR","JADAV VIVEK BHUPATBHAI","SACHIN ASHISHBHAI SONI","MANALI HARESHBHAI PANCHANI","JAY LALITBHAI BHALALA","HINA LALJIBHAI RATHOD","ASHISH ARVINDBHAI VORA","JADVANI HEPIL DILIPBHAI","HARDIK DAMJIBHAI KALSARIYA","GURJAR BHAVNA GANESH","KRUNAL KASHINATH JAIN","SAHILKUMAR MAGANBHAI BARAIYA","ARCHANA SANJAYBHAI DEVANI","NAIMISH RAJESHBHAI MARU","DHAMELIYA JEEL KETANBHAI","GAURI RAVINDRA MANANI","PARTH BALUBHAI KUMBHANI","KRINA CHANDRESHBHAI VEJANI","KRISH ANILBHAI GADHETHARIYA","PRATHAM KAMLESHBHAI GOHIL","MITUL BHARATBHAI RAVAL","LAX SURESHKUMAR SUHAGIYA","DHRUV SANJAYBHAI RAJPUT","RIYABEN DINESHBHAI NANERA","BHAVDIP SANJAYBHAI SONDAGAR","PARMAR MILANSINH VINODBHAI","HARESHBHAI NANJIBHAI PRAJAPATI","JANVI PANKAJBHAI MAKWANA","VINAYAK SUNILBHAI RAVAL","MEET MUKESHBHAI TAILOR","ASHISHKUMAR HIRENBHAI GOHIL","CHARUBEN JAMANBHAI MUNGARA","HARSHITA JAYSUKHBHAI KALSARIYA","YUG SHAILESHBHAI VAVADIYA","PRIYANKA JITENDRABHAI VALAND","NAMRATA MANGABHAI BARAIYA","KRISHNA HARESHBHAI VARIYA","DESAI ZIYA SANJAYBHAI","JANVI PREMJIBHAI VARSANI","HENI RAKESHBHAI PATEL","ZEEL NARESHBHAI MANGUKIYA","AENSI MAHESHKUMAR SAVALIYA","SHUHANI HARESHKUMAR VEGAD","RIDHAM GIRDHARBHAI ASLALIYA","KRISH MADHUBHAI KATARIYA","KEVIN MANUBHAI SONDAGAR","MAISURI VINUBHAI GAJERA","DEEP VIJAYBHAI VASOYA","RUTVI CHIRAGBHAI CHAVDA","JASH SUBHASHBHAI LATHIDADIYA","PRUTHVI BHAVESHBHAI GUJARATI","POOJA RAJESHBHAI GOHEL","SHANI HARESHBHAI KALENA","RUPARELIYA MANSI RAMESHBHAI","PARTH DHARMESHBHAI CHOTALIYA","NYUTIBEN SANDIPBHAI GHADIYA","DIMPAL DIPAKBHAI DHUMADIYA","RISHIKUMAR HARESHKUMAR JASOLIYA","VENSI MAHESHBHAI KARKAR","ASHMEET . KAUR","KEVIN MAHESHBHAI GHASKATA","ZIYA NILESHBHAI MANGUKIYA","YUG THAKARSHIBHAI PANDAV","DARSHIL BHARATBHAI SANGHANI","DRASHTI CHIRAGBHAI CHAUHAN","JAGWANI YASH TIKAM","RAVAL JAYDEV JATINBHAI","UDAY SAVJIBHAI PARMAR","URVISHA ARVINDBHAI TAPANIYA","RUDRA NARENDRABHAI TEJANI","PRACHI TULSHIBHAI AMBALIYA","NENCY VIJAYKUMAR KALASARIYA","DHARMIT PRAVINBHAI DESAI","POONAMBEN ARVINDBHAI JAISWAL","PRACHI JIGNESHBHAI BHAVSAR","PRINCE BHARATBHAI PORIYA","JENISHKUMAR GHANSHYAMBHAI DOBARIYA","SHIRGAONKAR PRAGATI RAKESHKUMAR","TANVI MUKESHBHAI KHUNT","GAUTAM NILESHBHAI BHAYANI","RUTVI DAMJIBHAI LATHIYA","KRISHNA BHARATBHAI MAKWANA","SHYAM KISHORBHAI RATHOD","DEV MANISHKUMAR DHAMECHA","PAL DINESHBHAI ITALIYA","SUKHDEV PRAKASHBHAI CHAUHAN","NEEL RASHIKBHAI CHOVATIYA","NENSIBEN SUBHASHBHAI KACHHADIYA","BHUMI JAYSUKHBHAI KAMANI","RONAK DHIRUBHAI SAVAJ","GANESH JIJABA YADAV","MAHEK ASHOKBHAI GHASKATA","DISHA ASHISHBHAI MANGROLIYA","DEVANSHIBEN MINESHBHAI PATEL","BHAVIK SURESHBHAI SAKARIYA","HARSIDDHI BHAVESHBHAI VEKARIYA","NIKITA RAVINDRABHAI CHAUDHARI","PRINCI SHAILESHBHAI AMBALIYA","POOJA ROSHANBHAI KANOJIYA","KAUSHIK VALLABHABHAI VAGHAMSHI","RENISH DILIPBHAI DUDHAT","MAHESHKUMAR BHARATBHAI MAKWANA","SHRADDHA SHAILESHBHAI BARAIYA","RAJPUT JANVIBEN AMARSINH","OM JAYESHBHAI DOBARIYA","GAURAV BHARATBHAI MAKVANA","KALATHIYA ABHI JAYSUKHBHAI","MITUL KISHORBHAI KATARIYA","ANIKET BHARATBHAI RANPISE","YASH VIJAYBHAI VAJA","MANAV JIGNESHBHAI MEPANI","AAYUSHKUMAR NARSANGBHAI SAGAR","HASTI MUKESHBHAI SAVALIYA","VAIBHAVI ASHVINBHAI VAGHASIYA","PRABHJYOTKAUR JARNAILSINGH GOUR","VAGHANI HITKUMAR BHIMJIBHAI","TRIJAL PARESHBHAI VYAS","CHANDU BHUPATBHAI MAKAVANA","JEEL JAYESHBHAI PATEL","KEVIL MEHULBHAI VAGHELA","NAGMA VAKIL ANSARI","KEVAL MANSUKHBHAI CHOTALIYA","VASOYA PRUTHVIKUMAR RAJUBHAI","NIRMAL BUDHESHBHAI GOHIL","KENA RAJESHKUMAR RAMOLIYA","TANISH RAMESHBHAI SANCHANIYA","MAHEK MOHANBHAI AMIPARA","NANDANI HARSHADBHAI GOHIL","KHUSHALI ASHOKBHAI MANDAVIYA","ZARANABEN JITUBHAI SIDDHPARA","DISHABEN ASHVINBHAI VAGHASIYA","TEJAS KALPESHBHAI VANECHA","EKTABEN ASHOKBHAI MALAVIYA","JANVI DIPAKBHAI VAGHELA","HARDI KANTIBHAI AMBALIYA","SANDIP ASHOKBHAI DOLAR","YAGNIK NALINBHAI MAKVANA","MOKSH CHETANBHAI SUTARIYA","HARSHAD RAMESHBHAI PARMAR","NISHTHA HITESHBHAI KATHIRIYA","DHARMI ASHVINBHAI GAJERA","ASHVI VIPULBHAI DHOLAKIYA","AMUL PRAVINBHAI KHADELA","PRAJAPATI KRISHNA RASIKBHAI","HETSVI PRAVINBHAI ANTALA","SACHIN KANUBHAI PRAJAPATI","YUG JITESHBHAI VAGHANI","JEEL MUKESHBHAI AGHERA","SRUSHTI BHAVESHBHAI GOLAKIYA","RAHUL SHIVKUMAR VISHWAKARMA","BHAKTIBEN PRAVINBHAI CHANDPARA","DEVANGI PANKAJBHAI VAGHELA","SAVAN DINESHBHAI NAVADIYA","AARJU KHIMJIBHAI PATEL","PRINCYBEN KARSHANBHAI ANTIYA","BHESANIYA YASVI NILESHBHAI","RUSHIK JAYSUKHBHAI GHOGHARI","MEET SURESHBHAI MANIYA","RIPALBEN RAJESHBHAI BHOI","DARSHAN RAJESHBHAI KIKANI","DHARMIK PRAVINBHAI GALANI","HARSHIT PARESHBHAI KALSARIYA","MOKSH JAGDISHBHAI SOJITRA","HENI MAHESHBHAI VEKARIYA","JANVI TULSIBHAI SOLANKI","TAMANNA VIPULBHAI JOSHI","PATADIYA RONIK ALPESHBHAI","PIYUSH CHATURBHAI MAKVANA","MOHIT JAYANTIBHAI CHAUHAN","NIRAJ VIPULBHAI DHOLARIYA","VIVEK BHIKHUBHAI KACHA","LATHIGARA MIHIR HARESHBHAI","AKSHIT DIPAKBHAI MIROLIYA","KAKADIYA TISHA RAMESHBHAI","KRISHA MAHESHBHAI PIPALIYA","JENISHBHAI LAVAJIBHAI SAVANI","FREYA MUKESHBHAI SHETA","HIYA HARSHADBHAI PATEL","VINASH SURESHBHAI BHESANIYA","VAIDIK RAKESHBHAI SAVALIYA","KRUNAL RAJUBHAI LAKKAD","VATSAL SURESHBHAI LATHIYA","JENIL RAMESHBHAI MAKWANA","YESHA ASHWINBHAI JASANI","MORADIYA VINAYAK PRAVINBHAI","RENSI NITESHBHAI VAGHANI","PARMAR SAHIL HARSHADBHAI","SHUBHAM HARCHANDBHAI PRAJAPATI","HIMESH LEKHCHAND NIMJE","SOLANKI ANIKET RAMESHBHAI","MEET DINESHBHAI DHOLA","PRINCE ASHVINBHAI GOTI","MOHIT JENTIBHAI ZANZAMERA"]
print(sdata[0])
for sname in sdata:
    print(sname)
    """
# ACCESSING LIST MEMBERS
print(a[0])  # AMROLI
print(a[-3]) # BSC DSA
print(a[2:5]) # BCA, BBA,BCOM
print(a[-3:-1]) # BSC DSA, BSC IT

# CHECK IF ITEM IS PRESENT USING IN OPERATOR
if "SUTEX1" in a:
    print("I AM PRESENT")
else:
    print("ITEM NOT FOUND")


    





    













