"""LIST METHODS IN PYTHON
USE OF LIST METHODS IN PROGRAMS
"""

print("List Methods: ")
print("-------------- ")
print("1. Append Method")
list1=["bca","bba","bcom"]
print(list1)
list1.append("mca")
print(list1)
list1.append("mba")
print(list1)

print("2. Clear Method")
print(list1)
list1.clear()
print(list1)

print("3. COPY Method")
print(list1)
list1.append("bca")
print(list1)
list1.append("bba")
print(list1)
list1.append("bcom")
print(list1)
list1.append("mca")
print(list1)
list1.append("mba")
print(list1)
list1.append("mcom")
print(list1)

print("COPY ITEMS OF LIST-1 to LIST-2")
list2 = list1.copy()
print(list2)

print("4. COUNT Method")
print(list1)
x = list1.count("mca")
print("TOTAL mca in LIST1 = ", x)


print("5. INDEX Method")
print(list1)
x= list1.index("bca")
print("BCA IS AT LOCATION : ", x)


print("6. INSERT Method")
print(list1)
list1.insert(0,"12th Science")
print(list1)
list1.insert(4,"bsc")
print(list1)
print("7. POP Method")
print(list1)
list1.pop(4)
print(list1)
print("8.REMOVE Method")
print(list1)
list1.remove("mca")
print(list1)
print("9.REVERSE Method")
print(list1)
list1.reverse()
print(list1)
print("10. SORT Method")
print(list1)
list1.sort()
print(list1)
print("10. SORT Method WITH DESCENDING ORDER")
print(list1)
list1.reverse()
print("LIST IN DESC ORDER")
print(list1)
